version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: spintechs

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080