spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: spintechs
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8090
qol:
  app:
    jwtSecret: qolSecretKey
    jwtExpirationMs: 86400000